export const customEmojis = [
  {
    name: "heart",
    shortNames: ["heart", "<3"],
    keywords: ["heart", "<3"],
    imageUrl: "/emotes/heart.png",
  },
  {
    name: "brokenheart",
    shortNames: ["brokenHeart"],
    keywords: ["broken", "heart", "broken heart", "brokenHeart"],
    imageUrl: "/emotes/brokenHeart.gif",
  },
  {
    name: "obama",
    shortNames: ["obama"],
    keywords: ["obama", "prism", "obamium"],
    imageUrl: "/emotes/obamium.png",
  },
  {
    name: "intelxamd",
    shortNames: ["intel"],
    keywords: ["intel", "amd", "intelxamd"],
    imageUrl: "/emotes/IntelxAMD.png",
  },
  {
    name: "linus",
    shortNames: ["linus"],
    keywords: ["linus", "tech", "linustechtips"],
    imageUrl: "/emotes/linus.png",
  },
  {
    name: "reddogehouse",
    shortNames: ["redDogeHouse"],
    keywords: ["red", "dogehouse", "doge"],
    imageUrl: "/emotes/reddogehouse.png",
  },
  {
    name: "this",
    shortNames: ["this"],
    keywords: ["this"],
    imageUrl: "/emotes/this.png",
  },
  {
    name: "browndogehouse",
    shortNames: ["brownDogeHouse"],
    keywords: ["brown", "dogehouse", "doge"],
    imageUrl: "/emotes/browndogehouse.png",
  },
  {
    name: "shut",
    shortNames: ["shut"],
    keywords: ["shut"],
    imageUrl: "/emotes/shut.png",
  },
  {
    name: "blobwtf",
    shortNames: ["blobWtf"],
    keywords: ["blob", "wtf"],
    imageUrl: "/emotes/blobwtf.png",
  },
  {
    name: "whalethonk",
    shortNames: ["WhaleThonk"],
    keywords: ["whale", "thonk", "thinking", "what"],
    imageUrl: "/emotes/whalethonk.png",
  },
  {
    name: "pogchamp",
    shortNames: ["PogChamp"],
    keywords: ["pogchamp", "pog"],
    imageUrl: "/emotes/pogchamp.png",
  },
  {
    name: "monkas",
    shortNames: ["monkaS"],
    keywords: ["monkas", "pepe"],
    imageUrl: "/emotes/monkas.png",
  },
  {
    name: "hypers",
    shortNames: ["HYPERS"],
    keywords: ["hypers", "pepe"],
    imageUrl: "/emotes/hypers.png",
  },
  {
    name: "peped",
    shortNames: ["pepeD"],
    keywords: ["peped", "pepe"],
    imageUrl: "/emotes/peped.gif",
  },
  {
    name: "pepega",
    shortNames: ["Pepega"],
    keywords: ["pepega", "pepe"],
    imageUrl: "/emotes/pepega.png",
  },
  {
    name: "peepohappy",
    shortNames: ["peepoHappy"],
    keywords: ["peepohappy", "peepo", "pepe"],
    imageUrl: "/emotes/peepohappy.png",
  },
  {
    name: "peepohug",
    shortNames: ["peepoHug"],
    keywords: ["peepohug", "peepo", "pepe"],
    imageUrl: "/emotes/peepohug.png",
  },
  {
    name: "sadge",
    shortNames: ["Sadge"],
    keywords: ["sadge", "pepe"],
    imageUrl: "/emotes/sadge.png",
  },
  {
    name: "catjam",
    shortNames: ["catJAM"],
    keywords: ["catjam", "vibe"],
    imageUrl: "/emotes/catjam.gif",
  },
  {
    name: "thonk",
    shortNames: ["Thonk"],
    keywords: ["thonk", "think"],
    imageUrl: "/emotes/thonk.png",
  },
  {
    name: "dogehouse",
    shortNames: ["DogeHouse"],
    keywords: ["dogehouse", "doge"],
    imageUrl: "/emotes/dogehouse.png",
  },
  {
    name: "sadhouse",
    shortNames: ["SadHouse"],
    keywords: ["dogehouse", "doge", "sadhouse"],
    imageUrl: "/emotes/sadhouse.png",
  },
  {
    name: "coolhouse",
    shortNames: ["CoolHouse"],
    keywords: ["dogehouse", "doge", "coolhouse"],
    imageUrl: "/emotes/coolhouse.png",
  },
  {
    name: "winkhouse",
    shortNames: ["WinkHouse"],
    keywords: ["dogehouse", "doge", "winkhouse"],
    imageUrl: "/emotes/winkhouse.png",
  },
  {
    name: "suprisehouse",
    shortNames: ["SupriseHouse"],
    keywords: ["dogehouse", "doge", "suprisehouse", "shock"],
    imageUrl: "/emotes/suprisehouse.png",
  },
  {
    name: "neutralhouse",
    shortNames: ["NeutralHouse"],
    keywords: ["dogehouse", "doge", "neutralhouse"],
    imageUrl: "/emotes/neutralhouse.png",
  },
  {
    name: "waytoodank",
    shortNames: ["WAYTOODANK"],
    keywords: ["dank", "feelsdankman", "waytoodank"],
    imageUrl: "/emotes/waytoodank.gif",
  },
  {
    name: "cryptobtc",
    shortNames: ["CryptoBTC"],
    keywords: ["crypto", "btc", "bitcoin"],
    imageUrl: "/emotes/cryptoBTC.png",
  },
  {
    name: "cryptoeth",
    shortNames: ["CryptoETH"],
    keywords: ["crypto", "eth", "ethereum"],
    imageUrl: "/emotes/cryptoETH.png",
  },
  {
    name: "cryptobnb",
    shortNames: ["CryptoBNB"],
    keywords: ["crypto", "bnb", "binance"],
    imageUrl: "/emotes/cryptoBNB.png",
  },
  {
    name: "cryptoltc",
    shortNames: ["CryptoLTC"],
    keywords: ["crypto", "ltc", "litecoin"],
    imageUrl: "/emotes/cryptoLTC.png",
  },
  {
    name: "cryptobch",
    shortNames: ["CryptoBCH"],
    keywords: ["crypto", "bch", "bitcoin", "bitcoincash"],
    imageUrl: "/emotes/cryptoBCH.png",
  },
  {
    name: "cryptodoge",
    shortNames: ["CryptoDOGE"],
    keywords: ["crypto", "doge", "dogecoin", "bestcoin"],
    imageUrl: "/emotes/cryptoDOGE.png",
  },
  {
    name: "cryptosushi",
    shortNames: ["CryptoSUSHI"],
    keywords: ["crypto", "sushi", "swap", "sushiswap"],
    imageUrl: "/emotes/cryptoSUSHI.png",
  },
  {
    name: "cryptotron",
    shortNames: ["CryptoTRON"],
    keywords: ["crypto", "tron"],
    imageUrl: "/emotes/cryptoTron.png",
  },
  {
    name: "cryptozec",
    shortNames: ["CryptoZEC"],
    keywords: ["crypto", "zec", "zcash"],
    imageUrl: "/emotes/cryptoZEC.png",
  },
  {
    name: "cryptoetc",
    shortNames: ["CryptoETC"],
    keywords: ["crypto", "etc", "ethereum", "ethereumclassic"],
    imageUrl: "/emotes/cryptoETC.png",
  },
  {
    name: "cryptocake",
    shortNames: ["CryptoCAKE"],
    keywords: ["crypto", "cake", "swap", "pancakeswap"],
    imageUrl: "/emotes/cryptoCAKE.png",
  },
  {
    name: "cryptoada",
    shortNames: ["CryptoADA"],
    keywords: ["crypto", "ada", "cardano"],
    imageUrl: "/emotes/cryptoADA.png",
  },
  {
    name: "cryptoxrp",
    shortNames: ["CryptoXRP"],
    keywords: ["crypto", "xrp", "ripple"],
    imageUrl: "/emotes/cryptoXRP.png",
  },
  {
    name: "cryptousdc",
    shortNames: ["CryptoUSDC"],
    keywords: ["crypto", "usdc", "usdcoin"],
    imageUrl: "/emotes/cryptoUSDC.png",
  },
  {
    name: "dodgycoin",
    shortNames: ["DodgyCoin"],
    keywords: ["crypto", "doge", "dodgycoin"],
    imageUrl: "/emotes/dodgyCoin.png",
  },
  {
    name: "pepebckl",
    shortNames: ["pepeBCKL"],
    keywords: [
      "pepebckl",
      "bckl",
      "pepe",
      "malarkey",
      "jesse",
      "penguin",
      "stallman",
      "freesoftware",
      "fsf",
      "charlie",
      "kernel",
      "lab",
      "kernellab",
      "computing",
      "jessecharlie",
      "linux",
      "torvalds",
    ],
    imageUrl: "/emotes/pepeBCKL.png",
  },
  {
    name: "5head",
    shortNames: ["5Head"],
    keywords: ["5head", "big", "brain", "bigbrain", "smart"],
    imageUrl: "/emotes/5Head.png",
  },
  {
    name: "ayaya",
    shortNames: ["AYAYA"],
    keywords: ["ayaya"],
    imageUrl: "/emotes/AYAYA.png",
  },
  {
    name: "babayep",
    shortNames: ["babaYEP"],
    keywords: ["babayep", "baba", "yep"],
    imageUrl: "/emotes/babaYEP.png",
  },
  {
    name: "bboomer",
    shortNames: ["BBoomer"],
    keywords: ["bboomer", "boomer"],
    imageUrl: "/emotes/BBoomer.gif",
  },
  {
    name: "bebela",
    shortNames: ["BebeLa"],
    keywords: ["bebela", "bebe"],
    imageUrl: "/emotes/BebeLa.png",
  },
  {
    name: "bern",
    shortNames: ["BERN"],
    keywords: [
      "bern",
      "notmeus",
      "bernie",
      "sanders",
      "berniesanders",
      "bernard",
      "socialism",
      "socialist",
      "comrade",
      "democrat",
      "malarkey",
      "biden",
      "joe",
      "joebiden",
      "us",
      "usa",
      "america",
    ],
    imageUrl: "/emotes/BERN.png",
  },
  {
    name: "bidenjam",
    shortNames: ["bidenJAM"],
    keywords: [
      "bidenjam",
      "jam",
      "jamjam",
      "malarkey",
      "ridinwithbiden",
      "icecream",
      "joe",
      "biden",
      "joebiden",
      "46",
      "president",
      "laser",
      "potus",
      "democrat",
      "us",
      "usa",
      "america",
    ],
    imageUrl: "/emotes/bidenJAM.gif",
  },
  {
    name: "playa",
    shortNames: ["Playa"],
    keywords: ["Playa"],
    imageUrl: "/emotes/Playa.png",
  },
  {
    name: "igetit",
    shortNames: ["IGetIt"],
    keywords: ["IGetIt", "Smile", "PepeLa", "Smug"],
    imageUrl: "/emotes/IGetIt.png",
  },
  {
    name: "blankies",
    shortNames: ["BLANKIES"],
    keywords: ["blankies", "jammies", "blanket", "dance"],
    imageUrl: "/emotes/BLANKIES.gif",
  },
  {
    name: "bogged",
    shortNames: ["BOGGED"],
    keywords: [
      "bogged",
      "bog",
      "hello",
      "phone",
      "iphone",
      "calling",
      "call",
      "phonecall",
    ],
    imageUrl: "/emotes/BOGGED.png",
  },
  {
    name: "clap",
    shortNames: ["Clap"],
    keywords: ["clap", "clapping"],
    imageUrl: "/emotes/Clap.gif",
  },
  {
    name: "coggers",
    shortNames: ["COGGERS"],
    keywords: ["coggers", "pog", "pogu", "poggies", "poggers", "pogger"],
    imageUrl: "/emotes/COGGERS.gif",
  },
  {
    name: "copium",
    shortNames: ["COPIUM"],
    keywords: ["copium", "cope"],
    imageUrl: "/emotes/COPIUM.png",
  },
  {
    name: "coronas",
    shortNames: ["coronaS"],
    keywords: ["coronas", "corona", "mask", "covid"],
    imageUrl: "/emotes/coronaS.png",
  },
  {
    name: "crabpls",
    shortNames: ["CrabPls"],
    keywords: ["crabpls", "crab", "pls", "plz", "please"],
    imageUrl: "/emotes/crabpls.gif",
  },
  {
    name: "dankhackermans",
    shortNames: ["DANKHACKERMANS"],
    keywords: [
      "dankhackermans",
      "dank",
      "hacker",
      "hackermans",
      "keyboard",
      "typing",
      "computer",
      "coding",
      "coder",
      "code",
      "virus",
      "malware",
    ],
    imageUrl: "/emotes/DANKHACKERMANS.gif",
  },
  {
    name: "dankhug",
    shortNames: ["dankHug"],
    keywords: ["dankhug", "dank", "hug"],
    imageUrl: "/emotes/dankHug.png",
  },
  {
    name: "dankies",
    shortNames: ["DANKIES"],
    keywords: ["dankies", "dank"],
    imageUrl: "/emotes/DANKIES.gif",
  },
  {
    name: "dewtime",
    shortNames: ["DewTime"],
    keywords: ["dewtime", "mountaindew", "dew", "moutain", "time"],
    imageUrl: "/emotes/DewTime.gif",
  },
  {
    name: "ez",
    shortNames: ["EZ"],
    keywords: ["ez"],
    imageUrl: "/emotes/EZ.png",
  },
  { name: "f", shortNames: ["F"], keywords: ["f"], imageUrl: "/emotes/F.gif" },
  {
    name: "feelsdankman",
    shortNames: ["FeelsDankMan"],
    keywords: ["feelsdankman", "feels", "feel", "dank", "man"],
    imageUrl: "/emotes/FeelsDankMan.png",
  },
  {
    name: "feelsokayman",
    shortNames: ["FeelsOkayMan"],
    keywords: ["feelsokayman", "feels", "feel", "okay", "man"],
    imageUrl: "/emotes/FeelsOkayMan.png",
  },
  {
    name: "feelsstrongman",
    shortNames: ["FeelsStrongMan"],
    keywords: ["feelsstrongman", "feels", "feel", "strong", "man"],
    imageUrl: "/emotes/FeelsStrongMan.png",
  },
  {
    name: "feelsweirdman",
    shortNames: ["FeelsWeirdMan"],
    keywords: ["feelsweirdman", "feels", "feel", "weird", "man"],
    imageUrl: "/emotes/FeelsWeirdMan.png",
  },
  {
    name: "gachihyper",
    shortNames: ["gachiHYPER"],
    keywords: ["gachihyper", "gachi", "hyper", "coomer"],
    imageUrl: "/emotes/gachiHYPER.gif",
  },
  {
    name: "grug",
    shortNames: ["GRUG"],
    keywords: ["grug"],
    imageUrl: "/emotes/GRUG.png",
  },
  {
    name: "guitartime",
    shortNames: ["GuitarTime"],
    keywords: ["guitartime", "guitar", "time"],
    imageUrl: "/emotes/GuitarTime.gif",
  },
  {
    name: "hackermans",
    shortNames: ["HACKERMANS"],
    keywords: [
      "hackermans",
      "hacker",
      "keyboard",
      "typing",
      "computer",
      "coding",
      "coder",
      "code",
      "virus",
      "malware",
    ],
    imageUrl: "/emotes/HACKERMANS.gif",
  },
  {
    name: "handsup",
    shortNames: ["HandsUp"],
    keywords: ["handsup", "hands", "up", "hand"],
    imageUrl: "/emotes/HandsUp.png",
  },
  {
    name: "hasanhypersmash",
    shortNames: ["hasanHyperSmash"],
    keywords: [
      "hasanhypersmash",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "hyper",
      "smash",
    ],
    imageUrl: "/emotes/hasanHyperSmash.gif",
  },
  {
    name: "hasansmash",
    shortNames: ["hasanSmash"],
    keywords: ["hasansmash", "hasan", "hasanabi", "hasanpiker", "smash"],
    imageUrl: "/emotes/hasanSmash.gif",
  },
  {
    name: "hasanwalk",
    shortNames: ["HasanWalk"],
    keywords: [
      "hasanwalk",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "walk",
      "walking",
    ],
    imageUrl: "/emotes/HasanWalk.gif",
  },
  {
    name: "hashyperjam",
    shortNames: ["hasHyperJAM"],
    keywords: [
      "hashyperjam",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "hyper",
      "jam",
      "jamjam",
      "jammies",
    ],
    imageUrl: "/emotes/hasHyperJAM.gif",
  },
  {
    name: "haspls",
    shortNames: ["hasPls"],
    keywords: [
      "haspls",
      "please",
      "pls",
      "plz",
      "hasan",
      "hasanabi",
      "hasanpiker",
    ],
    imageUrl: "/emotes/hasPls.gif",
  },
  {
    name: "hasrock",
    shortNames: ["hasRock"],
    keywords: [
      "hasrock",
      "spongebob",
      "patrick",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "rock",
    ],
    imageUrl: "/emotes/hasRock.gif",
  },
  {
    name: "hastasty",
    shortNames: ["hasTasty"],
    keywords: [
      "hastasty",
      "hasan",
      "tasty",
      "yum",
      "yummy",
      "hasanabi",
      "hasanpiker",
    ],
    imageUrl: "/emotes/hasTasty.gif",
  },
  {
    name: "hyperclap",
    shortNames: ["HYPERCLAP"],
    keywords: ["hyperclap", "hyper", "clap"],
    imageUrl: "/emotes/HYPERCLAP.gif",
  },
  {
    name: "hyperhammer",
    shortNames: ["hyperHammer"],
    keywords: ["hyperhammer", "hyper", "hammer"],
    imageUrl: "/emotes/hyperHammer.gif",
  },
  {
    name: "hyperitalianhands",
    shortNames: ["HYPERITALIANHANDS"],
    keywords: [
      "hyperitalianhands",
      "hyper",
      "italian",
      "hands",
      "hand",
      "italy",
      "ovahere",
    ],
    imageUrl: "/emotes/HYPERITALIANHANDS.gif",
  },
  {
    name: "hyperpogger",
    shortNames: ["HYPERPOGGER"],
    keywords: ["hyperpogger", "hyper", "pog", "pogger", "poggies"],
    imageUrl: "/emotes/HYPERPOGGER.gif",
  },
  {
    name: "hyperpogo",
    shortNames: ["HYPERPOGO"],
    keywords: [
      "hyperpogo",
      "hyper",
      "pog",
      "pogo",
      "azan",
      "poggies",
      "poggers",
      "pogger",
    ],
    imageUrl: "/emotes/HYPERPOGO.gif",
  },
  {
    name: "italianhands",
    shortNames: ["ItalianHands"],
    keywords: ["italianhands", "ovahere", "italian", "hands", "hand", "italy"],
    imageUrl: "/emotes/ItalianHands.gif",
  },
  {
    name: "jammies",
    shortNames: ["Jammies"],
    keywords: ["jammies", "jam", "jamjam", "dance", "vibe"],
    imageUrl: "/emotes/Jammies.gif",
  },
  {
    name: "kekw",
    shortNames: ["KEKW"],
    keywords: [
      "kekw",
      "kek",
      "omegalul",
      "lol",
      "lmao",
      "haha",
      "ha",
      "ja",
      "jaja",
    ],
    imageUrl: "/emotes/KEKW.png",
  },
  {
    name: "kekwait",
    shortNames: ["KEKWait"],
    keywords: [
      "kekwait",
      "lul",
      "omegalul",
      "lol",
      "lmao",
      "wait",
      "kek",
      "ha",
    ],
    imageUrl: "/emotes/KEKWait.png",
  },
  {
    name: "kkapitalist",
    shortNames: ["KKapitalist"],
    keywords: ["kkapitalist", "kapitalist", "capitalist", "business"],
    imageUrl: "/emotes/KKapitalist.png",
  },
  {
    name: "kkomrade",
    shortNames: ["KKomrade"],
    keywords: ["kkomrade", "komrade", "comrade"],
    imageUrl: "/emotes/KKomrade.png",
  },
  {
    name: "kkonaw",
    shortNames: ["KKonaW"],
    keywords: ["kkonaw"],
    imageUrl: "/emotes/KKonaW.png",
  },
  {
    name: "kkop",
    shortNames: ["KKop"],
    keywords: [
      "kkop",
      "kop",
      "kops",
      "cop",
      "cops",
      "police",
      "acab",
      "blueline",
    ],
    imageUrl: "/emotes/KKop.png",
  },
  {
    name: "lulw",
    shortNames: ["LULW"],
    keywords: ["lulw", "lul", "lol", "lmao", "omegalul"],
    imageUrl: "/emotes/LULW.png",
  },
  {
    name: "lulwut",
    shortNames: ["lulWut"],
    keywords: [
      "lulwut",
      "lul",
      "lmao",
      "lol",
      "wut",
      "what",
      "wat",
      "wtf",
      "omegalul",
      "ha",
      "haha",
      "ja",
      "jaja",
    ],
    imageUrl: "/emotes/lulWut.png",
  },
  {
    name: "malarkey",
    shortNames: ["MALARKEY"],
    keywords: [
      "malarkey",
      "ridinwithbiden",
      "icecream",
      "joe",
      "biden",
      "joebiden",
      "46",
      "president",
      "laser",
      "potus",
      "democrat",
      "us",
      "usa",
      "america",
    ],
    imageUrl: "/emotes/MALARKEY.gif",
  },
  {
    name: "mmmhmm",
    shortNames: ["MmmHmm"],
    keywords: [
      "mmmhmm",
      "mmm",
      "mmmm",
      "hmm",
      "hmmm",
      "mmmmhmmm",
      "mmmmhmm",
      "mmmhmmm",
    ],
    imageUrl: "/emotes/MmmHmm.gif",
  },
  {
    name: "modcheck",
    shortNames: ["modCheck"],
    keywords: [
      "modcheck",
      "mods",
      "mod",
      "check",
      "spongebob",
      "ask",
      "askers",
      "whoasked",
      "where",
      "look",
      "fish",
      "oooo",
    ],
    imageUrl: "/emotes/modCheck.gif",
  },
  {
    name: "modtime",
    shortNames: ["ModTime"],
    keywords: ["modtime", "mod", "mods", "time"],
    imageUrl: "/emotes/ModTime.gif",
  },
  {
    name: "monkahmm",
    shortNames: ["monkaHmm"],
    keywords: ["monkahmm", "monka", "hmmm", "hmm"],
    imageUrl: "/emotes/monkaHmm.png",
  },
  {
    name: "monkastare",
    shortNames: ["monkaStare"],
    keywords: ["monkastare", "stare", "monka"],
    imageUrl: "/emotes/monkaStare.png",
  },
  {
    name: "monkasteer",
    shortNames: ["monkaSTEER"],
    keywords: ["monkasteer", "monka", "steer", "ridinwithbiden"],
    imageUrl: "/emotes/monkaSTEER.gif",
  },
  {
    name: "monkaw",
    shortNames: ["monkaW"],
    keywords: ["monkaw", "monka"],
    imageUrl: "/emotes/monkaW.png",
  },
  {
    name: "neffhyperjam",
    shortNames: ["neffHyperJAM"],
    keywords: [
      "neffhyperjam",
      "hyperjam",
      "jam",
      "jammies",
      "boppin",
      "dj",
      "jamjam",
      "neff",
      "will",
      "willneff",
    ],
    imageUrl: "/emotes/neffHyperJAM.gif",
  },
  {
    name: "nodders",
    shortNames: ["NODDERS"],
    keywords: ["nodders", "nod", "noddies"],
    imageUrl: "/emotes/NODDERS.gif",
  },
  {
    name: "nopers",
    shortNames: ["NOPERS"],
    keywords: ["nopers", "no", "nope"],
    imageUrl: "/emotes/NOPERS.gif",
  },
  {
    name: "nymncorn",
    shortNames: ["nymnCorn"],
    keywords: ["nymncorn", "mmm", "corn", "nymn"],
    imageUrl: "/emotes/nymnCorn.gif",
  },
  {
    name: "okaychamp",
    shortNames: ["OkayChamp"],
    keywords: ["okaychamp", "okay", "champ"],
    imageUrl: "/emotes/OkayChamp.png",
  },
  {
    name: "omegalul",
    shortNames: ["OMEGALUL"],
    keywords: ["omegalul", "lol", "lmao", "lul", "ha", "haha", "ja", "jaja"],
    imageUrl: "/emotes/omegalul.png",
  },
  {
    name: "oooo",
    shortNames: ["OOOO"],
    keywords: ["oooo", "fish"],
    imageUrl: "/emotes/OOOO.gif",
  },
  {
    name: "pagchomp",
    shortNames: ["PagChomp"],
    keywords: ["pagchomp", "pag", "chomp"],
    imageUrl: "/emotes/PagChomp.png",
  },
  {
    name: "painschamp",
    shortNames: ["PainsChamp"],
    keywords: ["painschamp", "pains", "champ", "pain"],
    imageUrl: "/emotes/PainsChamp.png",
  },
  {
    name: "pausechamp",
    shortNames: ["PauseChamp"],
    keywords: ["pausechamp", "pause", "champ"],
    imageUrl: "/emotes/PauseChamp.png",
  },
  {
    name: "peepoarrive",
    shortNames: ["peepoArrive"],
    keywords: [
      "peepoarrive",
      "peepo",
      "pepo",
      "arrive",
      "here",
      "welcome",
      "hey",
      "wave",
      "hi",
      "hello",
      "howdy",
    ],
    imageUrl: "/emotes/peepoArrive.gif",
  },
  {
    name: "peepobaba",
    shortNames: ["peepoBaba"],
    keywords: ["peepobaba", "peepo", "pepo", "baba"],
    imageUrl: "/emotes/peepoBaba.png",
  },
  {
    name: "peepobye",
    shortNames: ["peepoBye"],
    keywords: ["peepobye", "peepo", "pepo", "bye"],
    imageUrl: "/emotes/peepoBye.gif",
  },
  {
    name: "peepochat",
    shortNames: ["peepoChat"],
    keywords: ["peepochat", "peepo", "pepo", "chat"],
    imageUrl: "/emotes/peepoChat.gif",
  },
  {
    name: "peepocheer",
    shortNames: ["peepoCheer"],
    keywords: ["peepocheer", "peepo", "pepo", "cheer"],
    imageUrl: "/emotes/peepoCheer.gif",
  },
  {
    name: "peepoclap",
    shortNames: ["peepoClap"],
    keywords: ["peepoclap", "peepo", "pepo", "clap"],
    imageUrl: "/emotes/peepoClap.gif",
  },
  {
    name: "peepod",
    shortNames: ["peepoD"],
    keywords: ["peepod", "peepo", "pepo"],
    imageUrl: "/emotes/peepoD.gif",
  },
  {
    name: "peepofat",
    shortNames: ["peepoFat"],
    keywords: ["peepofat", "peepo", "pepo", "fat", "houngry", "hungry", "food"],
    imageUrl: "/emotes/peepoFat.png",
  },
  {
    name: "peepogiggles",
    shortNames: ["peepoGiggles"],
    keywords: ["peepogiggles", "pepo", "peepo", "giggle", "giggles"],
    imageUrl: "/emotes/peepoGiggles.gif",
  },
  {
    name: "peepohey",
    shortNames: ["peepoHey"],
    keywords: [
      "peepohey",
      "peepo",
      "wave",
      "pepo",
      "hey",
      "hi",
      "hello",
      "howdy",
      "welcome",
    ],
    imageUrl: "/emotes/peepoHey.gif",
  },
  {
    name: "peepojammer",
    shortNames: ["peepoJAMMER"],
    keywords: ["peepojammer", "peepo", "pepo", "jam", "jammer", "jamjam"],
    imageUrl: "/emotes/peepoJAMMER.gif",
  },
  {
    name: "peepokiss",
    shortNames: ["peepoKiss"],
    keywords: ["peepokiss", "peepo", "pepo", "kiss", "love"],
    imageUrl: "/emotes/peepoKiss.png",
  },
  {
    name: "peepoleave",
    shortNames: ["peepoLeave"],
    keywords: ["peepoleave", "peepo", "pepo", "leave", "exit", "bye"],
    imageUrl: "/emotes/peepoLeave.gif",
  },
  {
    name: "peepopog",
    shortNames: ["peepoPog"],
    keywords: ["peepopog", "peepo", "pepo", "pog"],
    imageUrl: "/emotes/peepoPog.png",
  },
  {
    name: "peepopogo",
    shortNames: ["peepoPogO"],
    keywords: ["peepopogo", "peepo", "pepo", "pog", "pogo"],
    imageUrl: "/emotes/peepoPogO.png",
  },
  {
    name: "peeporun",
    shortNames: ["peepoRun"],
    keywords: ["peeporun", "peepo", "pepo", "run"],
    imageUrl: "/emotes/peepoRun.gif",
  },
  {
    name: "peeposhy",
    shortNames: ["peepoShy"],
    keywords: ["peeposhy", "peepo", "pepo", "shy"],
    imageUrl: "/emotes/peepoShy.gif",
  },
  {
    name: "peeposnow",
    shortNames: ["peepoSnow"],
    keywords: [
      "peeposnow",
      "peepo",
      "pepo",
      "snow",
      "christmas",
      "cold",
      "holidays",
    ],
    imageUrl: "/emotes/peepoSnow.gif",
  },
  {
    name: "peepot",
    shortNames: ["peepoT"],
    keywords: ["peepot", "peepo", "pepo"],
    imageUrl: "/emotes/peepoT.gif",
  },
  {
    name: "peepoweird",
    shortNames: ["peepoWeird"],
    keywords: ["peepoweird", "peepo", "pepo", "weird"],
    imageUrl: "/emotes/peepoWeird.png",
  },
  {
    name: "pepecd",
    shortNames: ["pepeCD"],
    keywords: ["pepecd", "pepe", "cd"],
    imageUrl: "/emotes/pepeCD.gif",
  },
  {
    name: "pepegehmm",
    shortNames: ["PepegeHmm"],
    keywords: ["pepegehmm", "pepege", "pepe", "hmm", "hmmm"],
    imageUrl: "/emotes/PepegeHmm.png",
  },
  {
    name: "pepehands",
    shortNames: ["PepeHands"],
    keywords: ["pepehands", "pepe", "hands"],
    imageUrl: "/emotes/PepeHands.png",
  },
  {
    name: "pepejamjam",
    shortNames: ["pepeJAMJAM"],
    keywords: ["pepejamjam", "pepe", "jam"],
    imageUrl: "/emotes/pepeJAMJAM.gif",
  },
  {
    name: "pepejam",
    shortNames: ["pepeJAM"],
    keywords: ["pepeJAM", "pepe"],
    imageUrl: "/emotes/pepejam.gif",
  },
  {
    name: "pepela",
    shortNames: ["PepeLa"],
    keywords: ["pepela", "pepe"],
    imageUrl: "/emotes/PepeLa.png",
  },
  {
    name: "pepelaugh",
    shortNames: ["PepeLaugh"],
    keywords: ["pepelaugh", "pepe", "laugh"],
    imageUrl: "/emotes/PepeLaugh.gif",
  },
  {
    name: "pepemeltdown",
    shortNames: ["pepeMeltdown"],
    keywords: ["pepemeltdown", "pepe", "meltdown"],
    imageUrl: "/emotes/pepeMeltdown.gif",
  },
  {
    name: "pepep",
    shortNames: ["pepeP"],
    keywords: ["pepep", "pepe"],
    imageUrl: "/emotes/pepeP.gif",
  },
  {
    name: "pepes",
    shortNames: ["PepeS"],
    keywords: ["pepes", "pepe"],
    imageUrl: "/emotes/PepeS.gif",
  },
  {
    name: "pepespit",
    shortNames: ["PepeSpit"],
    keywords: ["pepespit", "pepe", "spit"],
    imageUrl: "/emotes/PepeSpit.gif",
  },
  {
    name: "pepew",
    shortNames: ["pepeW"],
    keywords: ["pepew", "pepe"],
    imageUrl: "/emotes/pepeW.gif",
  },
  {
    name: "pepog",
    shortNames: ["PepoG"],
    keywords: ["pepog", "pepo", "peepo"],
    imageUrl: "/emotes/PepoG.png",
  },
  {
    name: "pog",
    shortNames: ["Pog"],
    keywords: ["pog", "poggies", "pogger", "poggers"],
    imageUrl: "/emotes/Pog.png",
  },
  {
    name: "poggers",
    shortNames: ["POGGERS"],
    keywords: ["poggers", "pog", "poggies", "pogger"],
    imageUrl: "/emotes/POGGERS.png",
  },
  {
    name: "poggies",
    shortNames: ["POGGIES"],
    keywords: ["poggies", "pog", "pogger"],
    imageUrl: "/emotes/POGGIES.png",
  },
  {
    name: "pogo",
    shortNames: ["PogO"],
    keywords: ["pogo", "pog", "azan"],
    imageUrl: "/emotes/PogO.png",
  },
  {
    name: "pogu",
    shortNames: ["PogU"],
    keywords: ["pogu", "pog"],
    imageUrl: "/emotes/PogU.png",
  },
  {
    name: "pphop",
    shortNames: ["ppHop"],
    keywords: ["pphop", "hop"],
    imageUrl: "/emotes/ppHop.gif",
  },
  {
    name: "ppoverheat",
    shortNames: ["ppOverheat"],
    keywords: ["ppoverheat", "overheat"],
    imageUrl: "/emotes/ppOverheat.gif",
  },
  {
    name: "pppoof",
    shortNames: ["ppPoof"],
    keywords: ["pppoof", "poof"],
    imageUrl: "/emotes/ppPoof.gif",
  },
  {
    name: "prayge",
    shortNames: ["Prayge"],
    keywords: ["prayge", "pray", "god"],
    imageUrl: "/emotes/Prayge.png",
  },
  {
    name: "ratjam",
    shortNames: ["ratJAM"],
    keywords: ["ratjam", "rat", "jam"],
    imageUrl: "/emotes/ratJAM.gif",
  },
  {
    name: "ree",
    shortNames: ["REE"],
    keywords: ["ree", "reeee"],
    imageUrl: "/emotes/REE.png",
  },
  {
    name: "sillychamp",
    shortNames: ["SillyChamp"],
    keywords: ["sillychamp", "silly", "champ"],
    imageUrl: "/emotes/SillyChamp.png",
  },
  {
    name: "smoketime",
    shortNames: ["SmokeTime"],
    keywords: ["smoketime", "smoke"],
    imageUrl: "/emotes/SmokeTime.gif",
  },
  {
    name: "swooner",
    shortNames: ["SWOONER"],
    keywords: ["swooner"],
    imageUrl: "/emotes/SWOONER.png",
  },
  {
    name: "teatime",
    shortNames: ["TeaTime"],
    keywords: ["teatime", "tea"],
    imageUrl: "/emotes/TeaTime.gif",
  },
  {
    name: "tomatotime",
    shortNames: ["TomatoTime"],
    keywords: ["tomatotime", "tomato"],
    imageUrl: "/emotes/TomatoTime.gif",
  },
  {
    name: "unpoggers",
    shortNames: ["unPOGGERS"],
    keywords: ["unpoggers", "poggers", "pog", "unpoggies"],
    imageUrl: "/emotes/unPOGGERS.png",
  },
  {
    name: "weirdchamp",
    shortNames: ["WeirdChamp"],
    keywords: ["weirdchamp", "weird", "champ"],
    imageUrl: "/emotes/WeirdChamp.png",
  },
  {
    name: "weirdge",
    shortNames: ["Weirdge"],
    keywords: ["weirdge", "weird"],
    imageUrl: "/emotes/Weirdge.png",
  },
  {
    name: "whatchamp",
    shortNames: ["WhatChamp"],
    keywords: ["whatchamp", "what", "champ"],
    imageUrl: "/emotes/WhatChamp.png",
  },
  {
    name: "wicked",
    shortNames: ["WICKED"],
    keywords: ["wicked"],
    imageUrl: "/emotes/WICKED.png",
  },
  {
    name: "widepeepohappy",
    shortNames: ["widepeepoHappy"],
    keywords: ["widepeepohappy", "peepohappy", "peepo", "happy"],
    imageUrl: "/emotes/widepeepoHappy.png",
  },
  {
    name: "widepeeposad",
    shortNames: ["widepeepoSad"],
    keywords: ["widepeeposad", "peeposad", "peepo", "sad"],
    imageUrl: "/emotes/widepeepoSad.png",
  },
  {
    name: "winetime",
    shortNames: ["WineTime"],
    keywords: ["winetime", "wine"],
    imageUrl: "/emotes/WineTime.gif",
  },
  {
    name: "yep",
    shortNames: ["YEP"],
    keywords: ["yep"],
    imageUrl: "/emotes/YEP.png",
  },
  {
    name: "zzoomer",
    shortNames: ["ZZoomer"],
    keywords: ["zzoomer", "zoomer"],
    imageUrl: "/emotes/ZZoomer.gif",
  },
  {
    name: "doge3d",
    shortNames: ["Doge3D"],
    keywords: ["doge3d", "doge", "3d"],
    imageUrl: "/emotes/doge3d.gif",
  },
  {
    name: "dogecool",
    shortNames: ["DogeCool"],
    keywords: ["dogecool", "doge", "cool"],
    imageUrl: "/emotes/dogecool.gif",
  },
  {
    name: "thugpepe",
    shortNames: ["ThugPepe"],
    keywords: ["dogehouse", "doge", "thugpepe"],
    imageUrl: "/emotes/thugpepe.png",
  },
  {
    name: "blaze",
    shortNames: ["blaze"],
    keywords: ["blaze", "yes", "snark"],
    imageUrl: "/emotes/blaze.png",
  },
  {
    name: "blobdance",
    shortNames: ["blobDance"],
    keywords: ["blobDance", "vibe"],
    imageUrl: "/emotes/blobdance.gif",
  },
  {
    name: "pepepls",
    shortNames: ["PepePls"],
    keywords: ["PepePls", "pepe"],
    imageUrl: "/emotes/pepepls.gif",
  },
  {
    name: "feelsgoodman",
    shortNames: ["FeelsGoodMan"],
    keywords: ["FeelsGoodMan", "pepe"],
    imageUrl: "/emotes/feelsgoodman.png",
  },
  {
    name: "github",
    shortNames: ["GitHub"],
    keywords: ["app", "git", "github"],
    imageUrl: "/emotes/github.png",
  },
  {
    name: "elixir",
    shortNames: ["Elixir"],
    keywords: ["app", "elixir"],
    imageUrl: "/emotes/elixir.png",
  },
  {
    name: "nextjs",
    shortNames: ["NextJS"],
    keywords: ["app", "next", "js"],
    imageUrl: "/emotes/nextjs.png",
  },
  {
    name: "react",
    shortNames: ["React"],
    keywords: ["app", "react", "js"],
    imageUrl: "/emotes/react.png",
  },
  {
    name: "electron",
    shortNames: ["Electron"],
    keywords: ["app", "electron"],
    imageUrl: "/emotes/electron.png",
  },
  {
    name: "beardguyr",
    shortNames: ["BeardGuyR"],
    keywords: ["meme", "beard", "guy"],
    imageUrl: "/emotes/beardguyright.png",
  },
  {
    name: "beardguyl",
    shortNames: ["BeardGuyL"],
    keywords: ["meme", "beard", "guy"],
    imageUrl: "/emotes/beardguyleft.png",
  },
  {
    name: "mememan",
    shortNames: ["MemeMan"],
    keywords: ["meme", "guy"],
    imageUrl: "/emotes/mememan.png",
  },
  {
    name: "npc",
    shortNames: ["NPC"],
    keywords: ["meme", "npc", "guy"],
    imageUrl: "/emotes/npc.png",
  },
  {
    name: "smudgecat",
    shortNames: ["SMudgeCat"],
    keywords: ["meme", "cat"],
    imageUrl: "/emotes/smudgecat.png",
  },
  {
    name: "stonks",
    shortNames: ["Stonks"],
    keywords: ["meme", "crypto", "guy"],
    imageUrl: "/emotes/stonks.png",
  },
  {
    name: "stinks",
    shortNames: ["Stinks"],
    keywords: ["meme", "crypto", "guy"],
    imageUrl: "/emotes/stinks.png",
  },
  {
    name: "iwmd",
    shortNames: ["IWMD"],
    keywords: ["meme", "dude", "wednesday", "frog"],
    imageUrl: "/emotes/wednesday.png",
  },
  {
    name: "presponge",
    shortNames: ["PreSponge"],
    keywords: ["meme", "spongebob"],
    imageUrl: "/emotes/presponge.png",
  },
  {
    name: "spongebob",
    shortNames: ["sPonGeBoB"],
    keywords: ["meme", "spongebob"],
    imageUrl: "/emotes/sPonGeBoB.png",
  },
  {
    name: "peepohappy",
    shortNames: ["peepohappy"],
    keywords: ["peepohappy", "peepo", "pepe"],
    imageUrl: "/emotes/peepohappy.png",
  },
  {
    name: "peepohug",
    shortNames: ["peepohug"],
    keywords: ["peepohug", "peepo", "pepe"],
    imageUrl: "/emotes/peepohug.png",
  },
  {
    name: "purpledogehouse",
    shortNames: ["PurpleDogeHouse"],
    keywords: ["purple", "dogehouse", "doge"],
    imageUrl: "/emotes/purpledogehouse.png",
  },
  {
    name: "widepeepopussy",
    shortNames: ["widepeepoPussy"],
    keywords: ["widepeepoPussy", "peepo", "wide"],
    imageUrl: "/emotes/widepeepoPussy.png",
  },
  {
    name: "rareparrot",
    shortNames: ["RareParrot"],
    keywords: ["Rare", "Parrot", "party"],
    imageUrl: "/emotes/rareParrot.gif",
  },
  {
    name: "orangedogehouse",
    shortNames: ["OrangeDogeHouse"],
    keywords: ["orange", "dogehouse", "doge"],
    imageUrl: "/emotes/orangedogehouse.png",
  },
  {
    name: "cyandogehouse",
    shortNames: ["CyanDogeHouse"],
    keywords: ["cyan", "dogehouse", "doge"],
    imageUrl: "/emotes/cyandogehouse.png",
  },
  {
    name: "angrykermit",
    shortNames: ["AngryKermit"],
    keywords: ["kermit", "angry", "ak47"],
    imageUrl: "/emotes/angrykermit.png",
  },
  {
    name: "darthkermit",
    shortNames: ["DarthKermit"],
    keywords: ["kermit", "star", "wars", "darth"],
    imageUrl: "/emotes/darthkermit.png",
  },
  {
    name: "takemymoney",
    shortNames: ["TakeMyMoney"],
    keywords: ["take", "my", "money", "shut", "up"],
    imageUrl: "/emotes/takemymoney.png",
  },
  {
    name: "awyeah",
    shortNames: ["awyeah"],
    keywords: ["aw", "yeah", "awyeah", "dancing"],
    imageUrl: "/emotes/awyeah.gif",
  },
  {
    name: "ztlul",
    shortNames: ["ztlul", "zerotwolul"],
    keywords: ["lul", "lol", "anime", "girl", "zerotwo"],
    imageUrl: "/emotes/zerotwolul.png",
  },
  {
    name: "ztsmug",
    shortNames: ["ztsmug", "zerotwosmug"],
    keywords: ["smug", "anime", "girl", "zerotwo"],
    imageUrl: "/emotes/zerotwosmug.png",
  },
  {
    name: "ztthinking",
    shortNames: ["ztthinking"],
    keywords: [
      "thinking",
      "think",
      "anime",
      "girl",
      "zerotwo",
      "zerotwothinking",
    ],
    imageUrl: "/emotes/zerotwothinking.png",
  },
  {
    name: "partyparrot",
    shortNames: ["partyparrot"],
    keywords: ["party", "high", "parrot", "fun"],
    imageUrl: "/emotes/PartyParrot.gif",
  },
  {
    name: "dogepls",
    shortNames: ["dogepls"],
    keywords: ["doge", "please", "fun", "dance"],
    imageUrl: "/emotes/DogePls.gif",
  },
  {
    name: "catdance",
    shortNames: ["catDance"],
    keywords: ["cat", "dance", "party", "fun"],
    imageUrl: "/emotes/catDance.gif",
  },
  {
    name: "doughdoge",
    shortNames: ["doughdoge"],
    keywords: ["dough", "doge", "pizza"],
    imageUrl: "/emotes/doughdoge.png",
  },
];

export const emoteMap: Record<string, string> = {};

export type CustomEmote = {
  name: string;
  shortNames: string[];
  keywords: string[];
  imageUrl: string;
};

customEmojis.forEach((e) => {
  emoteMap[e.name] = e.imageUrl;
});
